version: '2'
services:


    nginx:
        container_name: nginx-container1
        build: ./nginx
        restart: always
        ports:
        # - "8080:80"
        - "80:80"
        volumes:
        - api_data:/docker_api
        - ./log:/var/log/nginx
        depends_on:
        - api

    api:
        image: api-image:1.1
        build: ./api
        container_name: app
        restart: always
        # command: uwsgi  --emperor uwsgi.ini
        command: uwsgi --ini uwsgi.ini
        # ports:
        # - "8002:8000"
        volumes:
        - type: bind
         source: $HOST/location
         target: /container/location
       - type: volume
         source: mydata
         target: /docker_api/UserGroup
        - api_data:/docker_api


    # auto migrate django
    # migration:
    #     build: ./api
    #     command:
    #         - /bin/sh
    #         - -c
    #         - |
    #           python manage.py collectstatic --noinput
    #           python manage.py migrate
    #           python manage.py makemigrations musics
    #           python manage.py migrate
    #     volumes:
    #     - api_data:/docker_api
    #     depends_on:
    #     - db

volumes:
    api_data:
    pgdata:

